# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
 - task: Docker@2
   inputs:
     containerRegistry: 'acrktdcl_connection'
     repository: 'ktapp3_ktapp3'
     tags: $(Build.BuildId)
     command: 'buildAndPush'
     Dockerfile: '**/Prod.Dockerfile'
 - task: PublishPipelineArtifact@1
   inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: 'Files'