# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

# ASP.NET Core
- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'myAKSClusterConnection'
    namespace: 'CICD'
    command: 
    useConfigurationFile: true
    configuration: 'ktapp3-all-in-one.yaml'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'