apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gh-ktapp3
spec:
  replicas: 4
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: gh-ktapp3
    spec:
      containers:
      - name: gh-ktapp3
        image: brownbag.azurecr.io/gh_ktapp3:v4
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 200m
      - name: dataapi
        image: brownbag.azurecr.io/dataapi:v1
        ports:
        - containerPort: 4000
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: gh-ktapp3
spec:
  type: LoadBalancer
  ports:
  - port: 5000
  selector:
    app: gh-ktapp3
